### PR TITLE
fix: remain table and heading after delete all (close #377)

### LINKED ISSUE #377: In Wysiwyg, after select all contents and then delete, table or heading remain.
## Version

v1.3.0

## Test Environment

Chrome

## Current Behavior

screen recording 2019-01-30 at 2 07 57 pm mov
screen recording 2019-01-30 at 4 00 44 pm mov

If the wysiwyg contents start table or heading, table and heading is not removed after select all by pressing ctrl + a contents and then delete.

## Expected Behavior

Table and heading should be removed.

### PR DESCRIPTION
**Pull request by sohee-lee7**
### Please check if the PR fulfills these requirements
- [x] It's the right issue type on the title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [x] It does not introduce a breaking change or has a description of the breaking change

### Description

#377

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

File: src/js/wysiwygEditor.js [hunk 1]
```diff
@@ -523,6 +523,41 @@ class WysiwygEditor {
...
+      return false;
+    }
+
+    return true;
+  }
+
+  _isStartHeadingOrTableAndContainsThem(range) {
+    const {startContainer, startOffset, commonAncestorContainer, collapsed} = range;
+    const root = this.getEditor().getRoot();
+    const isHeadingOrTableRegexp = /^(TABLE|H[1-6])$/;
```
Comment (shiren) [inline src/js/wysiwygEditor.js]: 정규식은 함수내에서 만들지말고 모듈 스코프에두고 재사용하는게 나아요

File: src/js/wysiwygEditor.js [hunk 2]
```diff
@@ -523,6 +523,41 @@ class WysiwygEditor {
...
+
+    if (!collapsed && commonAncestorContainer === root) {
+      if (startContainer === root) {
+        return isHeadingOrTableRegexp.test(domUtils.getChildNodeByOffset(startContainer, startOffset).nodeName);
+      }
+
+      return startOffset === 0 && isHeadingOrTableRegexp.test(domUtils.getParentUntil(startContainer, root).nodeName);
```
Comment (shiren) [inline src/js/wysiwygEditor.js]: 이건 그냥 의견인데요 앞에는 if문을 사용하고 뒤에서는 엔드조건으로 조건문을 사용했는데 조건이 없으면 몰라도 일관성있게 else if로 처리하는게 더 잘 읽히는것 같아요
