### PR TITLE
fix: undo stack is incorrect in wysiwyg (close #381)

### LINKED ISSUE #381: If use placeholder, undo stack is incorrect in wysiwyg.
## Version

after this commit 8c7d95d025ca750b53bc383b26b4cdeca0f4146a

## Test Environment

Chrome

## Current Behavior

Step 1. create table
Step 2. ctrl + z (undo)
Step 3. ctrl + shift + z (redo)

Table does not appear.

## Expected Behavior

Table is created.

### PR DESCRIPTION
**Pull request by sohee-lee7**
### Please check if the PR fulfills these requirements
- [x] It's the right issue type on the title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [x] It does not introduce a breaking change or has a description of the breaking change

### Description

If placeholder class(`tui-editor-contents-placeholder`) is changed during undo, `_docWasChanged` of Squire occurs. So undostate change `false` and redo does not work.
`modifyDocument` of squire does not change undostate, so should use `modifyDocument` when change placeholder class.
(issue : #381)

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

File: src/js/wysiwygEditor.js [hunk 1]
```diff
@@ -438,12 +440,17 @@ class WysiwygEditor {
...
+    const squire = this.getEditor();
+    squire.modifyDocument(() => {
+      const root = squire.getRoot();
+      if (root.textContent || root.childNodes.length > 1) {
+        if (root.classList.contains(PLACEHOLDER_CSS_CLASSNAME)) {
+          root.classList.remove(PLACEHOLDER_CSS_CLASSNAME);
+        }
+      } else if (!root.classList.contains(PLACEHOLDER_CSS_CLASSNAME)) {
+        root.classList.add(PLACEHOLDER_CSS_CLASSNAME);
+      }
```
Comment (dongwoo-kim) [inline src/js/wysiwygEditor.js]: `classList`의 `add`나 `remove`는 `contains`로 확인할 필요 없이 그냥 호출해도 되지 않을까요?
어차피 `add`는 중복으로 할 수 없고, 해당 클래스가 없을 때는 `remove`를 호출해도 무시되니까요.

Comment (shiren) [reply src/js/wysiwygEditor.js]: 같은 의견입니다.
확인 코드 제거되면 코드가 매우 간결해지겠네요

Comment (sohee-lee7) [reply src/js/wysiwygEditor.js]: 앗.. 그렇네요. 반영하겠습니다.
