### PR TITLE
fix: tooltip is not updated properly (close #153)

### LINKED ISSUE #153: Tooltip is  Not updated properly
## Version

1.10

## Test Environment

All Browsers

## Current Behavior

- Go to https://nhnent.github.io/tui.editor/api/latest/tutorial-example00-demo.html
- Hover on Scroll On ,the tooltip is showing as **Auto scroll enabled**
- click Scroll On,it will be turned off
- Again Hover on Scroll off , you can still see the **Auto scroll enabled**
image
image

when i debugged the scrollsync i found out that inactive tool tip is set to tooltip

https://github.com/nhnent/tui.editor/blob/f306ecade9973ea5bc7556341161b973a9b79bfe/src/js/extensions/scrollSync/scrollSync.js#L70

where as in the button hover event we are displaying the text from _tooltip element
https://github.com/nhnent/tui.editor/blob/f306ecade9973ea5bc7556341161b973a9b79bfe/src/js/ui/button.js#L92

image

## Expected Behavior

The tool tip should update the _tooltip properly

### PR DESCRIPTION
**Pull request by kyuwoo-choi**
### Please check if the PR fulfills these requirements
- [x] It's the right issue type on the title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [x] It does not introduce a breaking change or has a description of the breaking change

### Description
#153 

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

File: src/js/extensions/scrollSync/scrollSync.js [hunk 1]
```diff
@@ -64,10 +64,10 @@ function scrollSyncExtension(editor) {
         button._onOut();
         if (isActive) {
           button.$el.addClass('active');
-          button.tooltip = TOOL_TIP.active;
+          button.setTooltip(TOOL_TIP.active);
         } else {
           button.$el.removeClass('active');
-          button.tooltip = TOOL_TIP.inActive;
+          button.setTooltip(TOOL_TIP.inActive);
```
Comment (seonim-ryu) [inline src/js/extensions/scrollSync/scrollSync.js]: `inactive`가 맞지 않나요? 왠지 꼭 `활성화 속에..` 이런 느낌이 드네요 ;ㅅ;

**Comment by seonim-ryu** [comment]
[6/14] 리뷰 완료하였습니다.

File: src/js/extensions/scrollSync/scrollSync.js (hunk 1 above)
Comment (kyuwoo-choi) [reply src/js/extensions/scrollSync/scrollSync.js]: 오! ㅋ 네 바꾸겠습니다.
